- name: Add Docker yum repo
  yum_repository:
    name: docker
    description: Docker YUM repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg


- name: Install docker
  yum:
    name:
      - docker-ce-19.03.9-3
      - docker-ce-cli-19.03.9-3
      - containerd.io
    state: present

- name: Ensure group "docker" exists
  group:
    name: docker
    state: present

- name: Add the user 'centos' to group 'docker'
  user:
    name: centos
    group: docker