- name: Add Docker yum repo
  yum_repository:
    name: docker
    description: Docker YUM repo
    baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
    gpgkey: https://download.docker.com/linux/centos/gpg


- name: Install docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present